### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by ZencoreCZ** [wakwak-koba/arduino-esp32#3]
Hi, would it be possible to add how to install in Arduino IDE?

**Comment by wakwak-koba** [comment]
I'm sorry. This repository is not maintained.
If you are interested in BLE, I highly recommend using NimBLE for arduino.
https://github.com/h2zero/NimBLE-Arduino

I'm also helping, but unlike the one that comes with the arduino, it's extremely complete.

**Comment by ZencoreCZ** [comment]
thanks, I try.
